# .github/workflows/stale-branches.yml

name: 'Audit Dependencies Periodically'

on:
  schedule:
    - cron: '0 7 * * 1' # Every Monday at 7am
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Audit Dependencies
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install dependencies
        run: npm install

      - name: Audit critical vulnerabilities
        run: npm run audit:critical
